language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="2.2.x"
  - SYMFONY_VERSION="2.3.x"
  - SYMFONY_VERSION="2.4.x"

before_script:
  - composer require symfony/config:${SYMFONY_VERSION} --no-update
  - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update
  - composer require symfony/http-kernel:${SYMFONY_VERSION} --no-update
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
